export const ROLEPLAY_ACTOR_IDS = [
  'boss-byte',
  'client-linh',
  'qa-an',
  'pm-trang',
  'teammate-minh',
  'mentor-nova',
  'biz-director-ha',
  'biz-client-thao',
  'biz-ops-vy',
  'arch-senior-khoa',
  'arch-client-mai',
  'arch-site-tuan',
  'pharm-senior-huong',
  'pharm-patient-long',
  'pharm-doctor-minh',
  'mkt-lead-khanh',
  'mkt-client-yen',
  'mkt-data-an',
  'fin-chief-lam',
  'fin-auditor-ngan',
  'fin-manager-trang',
  'legal-senior-phuc',
  'legal-client-linh',
  'legal-compliance-an',
  'ux-lead-minh',
  'ux-user-mai',
  'ux-pm-trang',
] as const;

export type RoleplayActorId = typeof ROLEPLAY_ACTOR_IDS[number];

export const ROLEPLAY_STAGE_IDS = [
  'drag-stage-1',
  'drag-stage-2',
  'drag-stage-3',
  'open-stage-4',
  'open-stage-5',
  'open-stage-6',
  'business-stage-1',
  'business-stage-2',
  'business-stage-3',
  'business-stage-4',
  'architecture-stage-1',
  'architecture-stage-2',
  'architecture-stage-3',
  'architecture-stage-4',
  'pharmacy-stage-1',
  'pharmacy-stage-2',
  'pharmacy-stage-3',
  'pharmacy-stage-4',
  'marketing-stage-1',
  'marketing-stage-2',
  'marketing-stage-3',
  'accounting-stage-1',
  'accounting-stage-2',
  'accounting-stage-3',
  'ecommerce-stage-1',
  'ecommerce-stage-2',
  'ecommerce-stage-3',
  'uiux-stage-1',
  'uiux-stage-2',
  'uiux-stage-3',
] as const;

export type RoleplayStageId = typeof ROLEPLAY_STAGE_IDS[number];

export type RoleplayStageMode = 'drag' | 'open';

export interface RoleplayActor {
  id: RoleplayActorId;
  name: string;
  role: string;
  company: string;
  avatar: string;
  portraitEmoji: string;
  accent: string;
  softAccent: string;
  mood: string;
  statusLabel: string;
  workspace: string;
  artifactIcon: string;
  description: string;
  personality: string;
  signatureLine: string;
  visualTags: string[];
}

export interface RoleplayScenario {
  id: RoleplayStageId;
  stageNumber: number;
  mode: RoleplayStageMode;
  actorId: RoleplayActorId;
  missionTitle: string;
  missionObjective: string;
  context: string;
  scene: string;
  initialQuestion?: string;
  maxConversationTurns: number;
}

function actor(
  id: RoleplayActorId,
  name: string,
  role: string,
  company: string,
  avatar: string,
  accent: string,
  softAccent: string,
  mood: string,
  statusLabel: string,
  workspace: string,
  artifactIcon: string,
  description: string,
  personality: string,
  signatureLine: string,
  visualTags: string[],
): RoleplayActor {
  return {
    id,
    name,
    role,
    company,
    avatar,
    portraitEmoji: avatar,
    accent,
    softAccent,
    mood,
    statusLabel,
    workspace,
    artifactIcon,
    description,
    personality,
    signatureLine,
    visualTags,
  };
}

export const roleplayActors: Record<RoleplayActorId, RoleplayActor> = {
  'boss-byte': actor(
    'boss-byte',
    'BOSS BYTE',
    'Technical Lead · Sếp trực tiếp',
    'Pixel Tech Corp',
    '👔',
    '#7c3aed',
    '#211944',
    'REVIEW MODE',
    'SẾP ĐANG NHÌN',
    'Phòng họp sprint · màn hình task đang đỏ',
    '💻',
    'Sếp kỹ thuật mặc vest/blazer tối màu. Nói thẳng, hơi gắt, thích người biết nghĩ trước khi bấm chạy.',
    'Thẳng thắn, thực tế, có thể cà khịa nhẹ khi task lỗi. Ghét kéo bừa và ghét câu trả lời vòng vo.',
    'Đừng kéo bừa. Bug thật ngoài đời không cho cậu nút undo đâu.',
    ['Vest công sở', 'Review task', 'Deadline', 'Gắt có lý'],
  ),
  'client-linh': actor(
    'client-linh',
    'CHỊ LINH',
    'Khách hàng doanh nghiệp · Operations Manager',
    'Nova Retail',
    '👩‍💼',
    '#ff9aaa',
    '#3a1d37',
    'ĐANG SỐT RUỘT',
    'KHÁCH ĐANG CHỜ',
    'Văn phòng khách hàng · báo cáo cần gửi trước cuộc họp',
    '📊',
    'Khách hàng công sở bận rộn, cần kết quả dùng được ngay.',
    'Thực tế, sốt ruột, đôi khi khó chịu nếu câu trả lời quá chung. Nói như khách hàng đang chờ deadline thật.',
    'Chị không cần nghe thuật ngữ đâu. Chị cần biết khi nào dùng được.',
    ['Nhu cầu thật', 'Dễ hiểu', 'Deadline', 'Giá trị sử dụng'],
  ),
  'qa-an': actor(
    'qa-an',
    'AN QA',
    'QA Engineer · Người chặn lỗi',
    'Pixel Tech Corp',
    '✅',
    '#63e6a8',
    '#112a27',
    'ISSUE DETECTED',
    'CASE ĐANG FAIL',
    'Bàn QA · test case đỏ ngay trước giờ demo',
    '🧪',
    'QA công sở kỹ tính, luôn soi lỗi trước khi sản phẩm bị khách hàng soi.',
    'Thẳng, soi lỗi, không dễ cho qua. Có thể gắt khi case fail nhưng luôn gắt vào lỗi công việc.',
    'Case này fail rồi. Đừng cố thuyết phục tôi là nó ổn.',
    ['Kiểm thử', 'Case biên', 'Điều kiện', 'Chất lượng'],
  ),
  'pm-trang': actor(
    'pm-trang',
    'CHỊ TRANG',
    'Project Manager · Người giữ deadline',
    'Pixel Tech Corp',
    '📋',
    '#ffb84d',
    '#3a2816',
    'DEADLINE ĐANG DÍ',
    'CHỌN ƯU TIÊN NGAY',
    'War room dự án · đồng hồ deadline vẫn đang chạy',
    '⏱️',
    'PM công sở quyết đoán, sát deadline, không chấp nhận câu hứa suông.',
    'Bình tĩnh nhưng gắt khi cần. Bắt người chơi chọn việc quan trọng nhất thay vì ôm hết rồi cầu may.',
    'Còn 30 phút. Tôi cần quyết định, không cần một bài thuyết trình.',
    ['Ưu tiên', 'Rủi ro', 'Tiến độ', 'Áp lực'],
  ),
  'teammate-minh': actor(
    'teammate-minh',
    'MINH',
    'Đồng đội · Frontend Developer',
    'Pixel Tech Corp',
    '👕',
    '#8be9fd',
    '#14263b',
    'ĐANG BỊ KẸT',
    'TEAM ĐANG CHỜ',
    'Kênh chat nhóm · task giao diện đang kẹt vì phần logic',
    '💬',
    'Nam nhân viên IT mặc sơ mi/polo, thân thiện nhưng cũng biết cà khịa khi cả nhóm bị kẹt.',
    'Nói như đồng đội chat nhóm: thân, đời, hơi áp lực, đôi khi đùa nhẹ nhưng vẫn muốn giải quyết việc.',
    'Cậu lo logic, tôi lo giao diện. Đừng để hai đứa sửa đè nhau là được.',
    ['Phối hợp', 'Giao tiếp', 'Chia sẻ tiến độ', 'Tin cậy'],
  ),
  'mentor-nova': actor(
    'mentor-nova',
    'MENTOR NOVA',
    'Career Mentor · Người phỏng vấn cuối',
    'Career Quest AI',
    '🧭',
    '#ffe066',
    '#312b17',
    'REFLECTION MODE',
    'CAREER INSIGHT',
    'Phòng phỏng vấn cuối · bản đồ năng lực đang được mở',
    '🧭',
    'Cố vấn công sở từng trải, không phán xét nhưng kéo người chơi nói thật thay vì nói cho đẹp.',
    'Điềm tĩnh, sâu, có thể nói thẳng. Không dỗ dành quá mức, không đạo lý, tập trung vào tín hiệu nghề nghiệp thật.',
    'Chọn nghề bằng câu văn mẫu thì dễ chọn nhầm lắm.',
    ['Tự nhận thức', 'Động lực', 'Phản tư', 'Định hướng'],
  ),

  'biz-director-ha': actor(
    'biz-director-ha',
    'ANH HÀ',
    'Business Director · Người chốt mục tiêu',
    'Nova Growth',
    '📈',
    '#7c3aed',
    '#211944',
    'TARGET ĐANG ĐỎ',
    'DOANH SỐ ĐANG RƠI',
    'Phòng họp kinh doanh · dashboard doanh số vừa tụt mạnh',
    '📈',
    'Giám đốc kinh doanh mặc vest, sắc bén, không thích quyết định theo cảm tính.',
    'Nói thẳng, thích dữ liệu, ghét đổ lỗi thị trường. Thúc người chơi tìm nguyên nhân thật và chọn hành động đo được.',
    'Đừng chữa doanh số bằng cảm giác. Đưa tôi số liệu và một hướng cứu được.',
    ['KPI', 'Dữ liệu', 'Tăng trưởng', 'Quyết định'],
  ),
  'biz-client-thao': actor(
    'biz-client-thao',
    'CHỊ THẢO',
    'Khách hàng lớn · Key Account',
    'BlueMart',
    '🤝',
    '#ff9aaa',
    '#3a1d37',
    'ĐANG MẤT KIÊN NHẪN',
    'KHÁCH LỚN CÓ THỂ RỜI ĐI',
    'Cuộc gọi với khách hàng lớn · hợp đồng sắp lung lay',
    '📞',
    'Khách hàng doanh nghiệp nói lịch sự nhưng rất cứng khi dịch vụ kém.',
    'Thực tế, sốt ruột, cần cam kết cụ thể. Không chấp nhận xin lỗi dài mà không có thời hạn xử lý.',
    'Chị không cần lời hứa đẹp. Chị cần biết lần này bên em sửa được gì.',
    ['Khách hàng', 'Cam kết', 'Dịch vụ', 'Giữ chân'],
  ),
  'biz-ops-vy': actor(
    'biz-ops-vy',
    'CHỊ VY',
    'Operations Lead · Người giữ vận hành',
    'Nova Growth',
    '🧩',
    '#ffb84d',
    '#3a2816',
    'VẬN HÀNH QUÁ TẢI',
    'CHỌN VIỆC CỨU TRƯỚC',
    'Bàn điều phối · đơn hàng tăng nhưng nhân sự không đủ',
    '🧩',
    'Lead vận hành quyết đoán, luôn nghĩ tới nguồn lực và rủi ro quá tải.',
    'Gắt khi người chơi ôm hết việc. Bắt chọn ưu tiên, bỏ bớt phần ít tác động và báo rủi ro sớm.',
    'Không phải cái gì cũng làm ngay. Việc quan trọng là biết bỏ cái gì.',
    ['Vận hành', 'Nguồn lực', 'Ưu tiên', 'Rủi ro'],
  ),

  'arch-senior-khoa': actor(
    'arch-senior-khoa',
    'KTS KHOA',
    'Senior Architect · Người review bản vẽ',
    'Atelier 9',
    '📐',
    '#ffe066',
    '#312b17',
    'REVIEW BẢN VẼ',
    'CÔNG NĂNG CHƯA ỔN',
    'Studio kiến trúc · bản vẽ đang mở trên màn hình lớn',
    '📐',
    'Kiến trúc sư trưởng giàu kinh nghiệm, nói ít nhưng soi rất kỹ công năng.',
    'Sâu, thẳng, không bị mê phối cảnh đẹp. Luôn kéo người chơi về công năng, trải nghiệm ở thật và an toàn.',
    'Nhà đẹp mà ở mệt thì không phải thiết kế tốt.',
    ['Công năng', 'Thẩm mỹ', 'An toàn', 'Bản vẽ'],
  ),
  'arch-client-mai': actor(
    'arch-client-mai',
    'CHỊ MAI',
    'Chủ nhà · Khách hàng thiết kế',
    'Dự án nhà phố',
    '🏠',
    '#ff9aaa',
    '#3a1d37',
    'KHÁCH ĐỔI Ý',
    'YÊU CẦU ĐANG PHÌNH RA',
    'Cuộc họp với chủ nhà · danh sách mong muốn dài hơn diện tích thật',
    '🏠',
    'Chủ nhà có nhiều mong muốn, thích đẹp nhưng chưa hiểu giới hạn diện tích và ngân sách.',
    'Nói đời, đôi lúc cảm tính. Cần người chơi biết hỏi lại, giải thích và không chiều khách mù quáng.',
    'Chị muốn đẹp, nhưng chị cũng muốn ở thoải mái. Em nói thật giúp chị đi.',
    ['Khách hàng', 'Diện tích', 'Ngân sách', 'Thuyết phục'],
  ),
  'arch-site-tuan': actor(
    'arch-site-tuan',
    'ANH TUẤN',
    'Site Engineer · Người ở công trường',
    'Atelier 9',
    '🦺',
    '#63e6a8',
    '#112a27',
    'CÔNG TRƯỜNG BÁO LỖI',
    'CHI TIẾT KHÔNG THI CÔNG ĐƯỢC',
    'Công trường · một chi tiết đẹp trên bản vẽ đang gây rủi ro khi thi công',
    '🦺',
    'Kỹ sư công trường thực tế, ưu tiên thi công được và an toàn hơn hình ảnh đẹp.',
    'Thẳng, thực dụng, ghét bản vẽ đẹp nhưng không thể làm ngoài công trường. Bắt người chơi giải thích phương án thay thế.',
    'Bản vẽ đẹp mấy mà công trường không làm được thì cũng nằm trên giấy thôi.',
    ['Thi công', 'An toàn', 'Chi phí', 'Hiện trường'],
  ),

  'pharm-senior-huong': actor(
    'pharm-senior-huong',
    'DS HƯƠNG',
    'Dược sĩ phụ trách · Người kiểm soát tư vấn',
    'CarePlus Pharmacy',
    '💊',
    '#ffb84d',
    '#3a2816',
    'QUẦY ĐANG ĐÔNG',
    'TƯ VẤN PHẢI CHẮC',
    'Nhà thuốc · khách xếp hàng nhưng tư vấn không được đoán mò',
    '💊',
    'Dược sĩ phụ trách nghiêm, ưu tiên hỏi đúng thông tin và biết giới hạn trách nhiệm.',
    'Thẳng, kỹ, không cho qua các câu tư vấn thiếu thông tin. Nhắc người chơi hỏi tuổi, triệu chứng, thuốc đang dùng, tiền sử và dấu hiệu cần đi khám.',
    'Ở quầy thuốc, nhanh không có nghĩa là được phép đoán.',
    ['Tư vấn', 'An toàn', 'Tiền sử', 'Chuyển tuyến'],
  ),
  'pharm-patient-long': actor(
    'pharm-patient-long',
    'ANH LONG',
    'Khách mua thuốc · Đang sốt ruột',
    'CarePlus Pharmacy',
    '🤒',
    '#8be9fd',
    '#14263b',
    'MUỐN MUA NHANH',
    'KHÁCH ĐANG NÓNG RUỘT',
    'Quầy thuốc · khách muốn mua thuốc nhanh và không muốn trả lời nhiều',
    '🤒',
    'Khách hàng ngoài đời: vội, hơi khó chịu, muốn có thuốc ngay dù thông tin chưa đủ.',
    'Nói như người bệnh đang mệt. Có thể gắt nhẹ nếu bị hỏi nhiều, nhưng sẽ hợp tác nếu người chơi giải thích dễ hiểu.',
    'Anh chỉ cần thuốc thôi, hỏi nhiều vậy có cần thiết không?',
    ['Khách hàng', 'Triệu chứng', 'Kiên nhẫn', 'Giải thích'],
  ),
  'pharm-doctor-minh': actor(
    'pharm-doctor-minh',
    'BS MINH',
    'Bác sĩ phối hợp · Người kiểm tra rủi ro',
    'CarePlus Clinic',
    '🩺',
    '#63e6a8',
    '#112a27',
    'ĐƠN THUỐC CẦN KIỂM TRA',
    'CÓ DẤU HIỆU PHẢI HỎI LẠI',
    'Cuộc gọi với phòng khám · đơn thuốc có điểm chưa rõ',
    '🩺',
    'Bác sĩ phối hợp, bình tĩnh nhưng rất nghiêm với tương tác thuốc và chỉ định không rõ.',
    'Nói chuyên môn, thận trọng. Muốn người chơi biết khi nào cần xác nhận lại thay vì tự suy đoán.',
    'Không chắc thì hỏi lại. Đoán trong y dược là thứ rất đắt.',
    ['Đơn thuốc', 'Tương tác', 'Xác nhận', 'Trách nhiệm'],
  ),

  'mkt-lead-khanh': actor('mkt-lead-khanh', 'ANH KHÁNH', 'Marketing Lead · Người giữ campaign', 'BuzzLab', '📣', '#7c3aed', '#211944', 'CAMPAIGN ĐANG LỆCH', 'CẦN INSIGHT THẬT', 'Phòng campaign · bảng số liệu tụt engagement', '📣', 'Marketing lead sắc, thích insight hơn ý tưởng màu mè.', 'Dí deadline, ghét content theo cảm hứng mà không hiểu khách hàng.', 'Ý tưởng hay mà sai insight thì vẫn là đốt ngân sách.', ['Insight', 'Campaign', 'Thông điệp', 'KPI']),
  'mkt-client-yen': actor('mkt-client-yen', 'CHỊ YẾN', 'Brand Client · Người duyệt thông điệp', 'Lumi Brand', '🗣️', '#ff9aaa', '#3a1d37', 'KHÁCH CHƯA DUYỆT', 'THÔNG ĐIỆP CHƯA TRÚNG', 'Cuộc gọi duyệt campaign · khách chưa hài lòng', '🗣️', 'Khách hàng brand khó tính, muốn thông điệp rõ và ít sáo rỗng.', 'Thực tế, hơi khó chịu nếu câu chữ đẹp nhưng không bán được.', 'Chị không cần câu hay trên giấy, chị cần khách hiểu và muốn bấm.', ['Brand', 'Thông điệp', 'Khách hàng', 'Duyệt bài']),
  'mkt-data-an': actor('mkt-data-an', 'AN DATA', 'Marketing Analyst · Người soi số', 'BuzzLab', '📊', '#63e6a8', '#112a27', 'SỐ LIỆU ĐANG LỆCH', 'ĐỪNG ĐOÁN MÒ', 'Bàn phân tích · CTR tụt nhưng team chưa rõ nguyên nhân', '📊', 'Analyst kỹ tính, kéo mọi ý tưởng về số liệu.', 'Không tin cảm giác. Bắt người chơi phân biệt giả thuyết, chỉ số và hành động test.', 'Không có số liệu thì đừng gọi nó là insight.', ['Data', 'A/B test', 'CTR', 'Giả thuyết']),

  'fin-chief-lam': actor('fin-chief-lam', 'ANH LÂM', 'Kế toán trưởng · Người chốt báo cáo', 'FinCore', '🧾', '#7c3aed', '#211944', 'SỐ LIỆU CHÊNH', 'BÁO CÁO CHƯA KHÓA', 'Phòng kế toán · file đối chiếu đang lệch trước hạn nộp', '🧾', 'Kế toán trưởng nghiêm, cực ghét đoán số.', 'Thẳng, kỹ, bắt người chơi đối chiếu chứng từ và ghi nhận rủi ro trước khi nộp báo cáo.', 'Số lệch không tự hết vì mình mong nó hết.', ['Chứng từ', 'Đối chiếu', 'Báo cáo', 'Kiểm soát']),
  'fin-auditor-ngan': actor('fin-auditor-ngan', 'CHỊ NGÂN', 'Kiểm toán nội bộ · Người soi chứng từ', 'FinCore', '🔎', '#63e6a8', '#112a27', 'CHỨNG TỪ THIẾU', 'KHÔNG ĐƯỢC GHI BỪA', 'Bàn kiểm soát · một khoản chi thiếu căn cứ', '🔎', 'Kiểm toán nội bộ kỹ, hỏi đến cùng về căn cứ.', 'Không dễ tin giải thích miệng. Bắt người chơi nói bằng chứng và cách xử lý thiếu chứng từ.', 'Không có chứng từ thì đừng biến nó thành số đẹp.', ['Kiểm toán', 'Bằng chứng', 'Tuân thủ', 'Rủi ro']),
  'fin-manager-trang': actor('fin-manager-trang', 'CHỊ TRANG', 'Finance Manager · Người giữ hạn báo cáo', 'FinCore', '⏱️', '#ffb84d', '#3a2816', 'HẠN NỘP ĐANG DÍ', 'CHỌN PHẦN KIỂM TRƯỚC', 'Cuộc họp tài chính · deadline nộp báo cáo sát giờ', '⏱️', 'Quản lý tài chính thực tế, cần ưu tiên phần rủi ro cao trước.', 'Gắt khi người chơi cố làm hết trong khi thời gian không đủ.', 'Không kiểm hết được thì kiểm đúng phần nguy hiểm nhất trước.', ['Deadline', 'Tài chính', 'Ưu tiên', 'Rủi ro']),

  'legal-senior-phuc': actor('legal-senior-phuc', 'ANH HUY', 'E-commerce Lead · Người giữ doanh thu sàn', 'MarketFlow', '🛒', '#7c3aed', '#211944', 'GMV ĐANG TỤT', 'ĐỪNG ĐOÁN MÒ', 'Phòng vận hành sàn · dashboard đơn hàng và chuyển đổi đang đỏ', '🛒', 'Lead thương mại điện tử mặc blazer công sở, nhìn số liệu nhanh và ghét tối ưu theo cảm giác.', 'Thẳng, thực tế, hơi cà khịa. Bắt người chơi nối được traffic, chuyển đổi, tồn kho và trải nghiệm khách.', 'Traffic có mà không ra đơn thì đừng vội đổ lỗi thuật toán.', ['Gian hàng', 'Conversion', 'Sàn TMĐT', 'Doanh thu']),
  'legal-client-linh': actor('legal-client-linh', 'CHỊ MAI', 'Khách online · Người đang bực vì đơn lỗi', 'MarketFlow', '📦', '#ff9aaa', '#3a1d37', 'KHÁCH ĐANG BỰC', 'NGUY CƠ 1 SAO', 'Kênh chat chăm sóc khách hàng · khách vừa báo nhận sai hàng', '📦', 'Khách mua online thực tế, sốt ruột, cần được xử lý nhanh và rõ mốc.', 'Không thích xin lỗi dài. Chỉ cần biết shop chịu trách nhiệm thế nào và bao giờ xong.', 'Chị mua hàng chứ không mua lời hứa. Em xử lý cụ thể sao?', ['Khách hàng', 'Đơn lỗi', 'Đánh giá', 'Uy tín shop']),
  'legal-compliance-an': actor('legal-compliance-an', 'AN OPS', 'Marketplace Ops · Người giữ vận hành flash sale', 'MarketFlow', '⚡', '#63e6a8', '#112a27', 'FLASH SALE ĐANG NGHẼN', 'CẨN THẬN VỠ ĐƠN', 'War room vận hành · đơn tăng nhanh hơn khả năng xử lý', '⚡', 'Nhân sự vận hành sàn kỹ tính, nhìn thấy rủi ro hủy đơn trước khi team marketing kịp ăn mừng.', 'Nhanh, sắc, hơi gắt khi người chơi chỉ muốn đẩy đơn mà quên kho, chat và giao hàng.', 'Bán được mà hủy hàng loạt thì không gọi là thắng, gọi là tự đốt shop.', ['Flash sale', 'Kho', 'Chat khách', 'Vận chuyển']),

  'ux-lead-minh': actor('ux-lead-minh', 'ANH MINH', 'UX Lead · Người review flow', 'Pixel Product', '🎨', '#8be9fd', '#14263b', 'FLOW ĐANG RỐI', 'NGƯỜI DÙNG BỊ KẸT', 'Phòng product · prototype đang bị người dùng bỏ giữa chừng', '🎨', 'UX lead thân nhưng kỹ, ghét thiết kế đẹp mà khó dùng.', 'Nói đời, có chút hài, bắt người chơi bảo vệ quyết định bằng hành vi người dùng.', 'Đẹp mà người dùng không bấm được thì chỉ là poster.', ['Flow', 'User', 'Prototype', 'Usability']),
  'ux-user-mai': actor('ux-user-mai', 'CHỊ MAI', 'Người dùng thử · Không rành công nghệ', 'User Test Lab', '👤', '#ff9aaa', '#3a1d37', 'USER ĐANG BỐI RỐI', 'KHÔNG TÌM THẤY NÚT', 'Phòng test người dùng · user đang loay hoay trên prototype', '👤', 'Người dùng thật, nói đơn giản, phản ứng theo cảm giác sử dụng.', 'Thật thà, dễ bối rối. Buộc người chơi giải thích bằng ngôn ngữ người dùng, không dùng jargon.', 'Chị không thấy nút đó ở đâu cả. Nó nằm chỗ nào vậy?', ['User test', 'Dễ hiểu', 'Quan sát', 'Hành vi']),
  'ux-pm-trang': actor('ux-pm-trang', 'CHỊ TRANG', 'Product Manager · Người chốt ưu tiên', 'Pixel Product', '📋', '#ffb84d', '#3a2816', 'SPRINT SẮP CHỐT', 'CHỌN FLOW CỨU TRƯỚC', 'Cuộc họp product · dev chỉ còn thời gian sửa một flow', '📋', 'PM product thực tế, bắt cắt scope và chọn impact cao nhất.', 'Gắt khi người chơi muốn sửa hết. Thích quyết định có tác động đo được.', 'Không có thời gian sửa hết. Chọn flow khiến người dùng kẹt nhất trước.', ['Product', 'Ưu tiên', 'Impact', 'Scope']),
};

function openScenario(
  id: RoleplayStageId,
  stageNumber: number,
  actorId: RoleplayActorId,
  missionTitle: string,
  missionObjective: string,
  context: string,
  scene: string,
  initialQuestion: string,
  maxConversationTurns = 2,
): RoleplayScenario {
  return {
    id,
    stageNumber,
    mode: 'open',
    actorId,
    missionTitle,
    missionObjective,
    context,
    scene,
    initialQuestion,
    maxConversationTurns,
  };
}

export const roleplayScenarios: RoleplayScenario[] = [
  {
    id: 'drag-stage-1',
    stageNumber: 1,
    mode: 'drag',
    actorId: 'boss-byte',
    missionTitle: 'TASK ĐẦU: ĐỪNG KÉO BỪA',
    missionObjective: 'Sắp xếp quy trình nhỏ đầu tiên: lấy đủ dữ liệu, xử lý đúng lúc, rồi mới trả kết quả.',
    context: 'Ngày thử việc đầu tiên. Boss Byte không cần bạn giỏi ngay, nhưng muốn thấy bạn nghĩ theo luồng chạy chứ không đoán mò.',
    scene: 'Bạn vừa ngồi vào bàn thì sếp đẩy task đầu tiên qua màn hình. Không khí như buổi thử việc thật: làm được thì đi tiếp, kéo bừa là bị soi ngay.',
    maxConversationTurns: 0,
  },
  {
    id: 'drag-stage-2',
    stageNumber: 2,
    mode: 'drag',
    actorId: 'client-linh',
    missionTitle: 'KHÁCH ĐANG CHỜ FILE BÁO CÁO',
    missionObjective: 'Xử lý cả danh sách số liệu, không làm thủ công từng dòng.',
    context: 'Chị Linh đang cần báo cáo để gửi trong cuộc họp. Chị không có thời gian nghe giải thích vòng vo.',
    scene: 'Chị Linh đang chuẩn bị vào họp. File báo cáo nhiều dòng số liệu, làm tay từng dòng là trễ chắc.',
    maxConversationTurns: 0,
  },
  {
    id: 'drag-stage-3',
    stageNumber: 3,
    mode: 'drag',
    actorId: 'qa-an',
    missionTitle: 'QA CHẶN RELEASE',
    missionObjective: 'Đừng xử lý bừa. Phải kiểm tra dữ liệu trước khi cho nó đi tiếp.',
    context: 'QA An vừa chặn bản bàn giao vì có dữ liệu không hợp lệ vẫn bị đưa vào xử lý.',
    scene: 'QA An đặt tablet xuống bàn. Test case đỏ ngay trước giờ demo, và bạn phải sửa luồng trước khi bản này đi tiếp.',
    maxConversationTurns: 0,
  },
  openScenario('open-stage-4', 4, 'pm-trang', '30 PHÚT NỮA BÀN GIAO', 'Thể hiện cách bạn xác định ưu tiên, xử lý rủi ro và giao tiếp khi thời gian rất ít.', 'Task bị lệch kết quả ngay sát giờ bàn giao. PM Trang cần bạn nói cách cứu tình hình ngay bây giờ.', 'War room im lặng bất thường. Đồng hồ vẫn chạy, còn PM Trang thì đang nhìn thẳng vào bạn.', 'Còn 30 phút nữa là bàn giao. Em chọn cứu phần nào trước, phần nào tạm để sau?'),
  openScenario('open-stage-5', 5, 'teammate-minh', 'ĐỒNG ĐỘI BỊ KẸT VÌ PHẦN CỦA BẠN', 'Nói chuyện với đồng đội sao cho rõ việc, không đẩy lỗi và không làm cả nhóm đứng hình.', 'Minh đang chờ phần của bạn để làm tiếp. Kênh chat nhóm bắt đầu réo tên bạn rồi.', 'Tin nhắn trong nhóm bắt đầu dồn dập. Minh không cáu, nhưng rõ ràng cậu ấy đang bị kẹt vì bạn.', 'Ê, phần của tớ đang kẹt vì phần của cậu. Mình chia lại việc sao cho kịp đây?'),
  openScenario('open-stage-6', 6, 'mentor-nova', 'NGỒI LẠI NÓI THẬT', 'Nói thật xem phần nào khiến bạn có hứng, phần nào làm bạn muốn bỏ cuộc.', 'Sau mấy tình huống vừa rồi, Mentor Nova muốn nghe điều thật nhất, không phải câu trả lời cho đẹp.', 'Màn hình kết quả tạm tắt. Mentor Nova kéo ghế ngồi xuống và hỏi bạn như một người từng trải.', 'Nhìn lại cả buổi đi. Đoạn nào làm bạn thấy có hứng, đoạn nào làm bạn muốn buông chuột?'),

  openScenario('business-stage-1', 1, 'biz-director-ha', 'DOANH SỐ RƠI TRƯỚC CUỘC HỌP', 'Đọc tín hiệu kinh doanh, chọn giả thuyết chính và nói hướng xử lý có dữ liệu.', 'Dashboard sáng nay báo doanh số một nhóm sản phẩm giảm mạnh. Anh Hà cần bạn nói hướng xử lý trước khi vào họp.', 'Phòng họp kinh doanh đang nóng. Ai cũng có ý kiến, nhưng chưa ai chỉ ra nguyên nhân có dữ liệu.', 'Doanh số rơi như vậy, em kiểm tra gì trước và đề xuất hành động đầu tiên thế nào?'),
  openScenario('business-stage-2', 2, 'biz-client-thao', 'KHÁCH LỚN ĐE DỌA RỜI ĐI', 'Xử lý khách hàng đang bực bằng phản hồi có trách nhiệm, mốc thời gian và phương án giữ chân.', 'Khách hàng lớn phàn nàn dịch vụ chậm. Nếu lần này trả lời mơ hồ, họ có thể chuyển sang nhà cung cấp khác.', 'Cuộc gọi với khách hàng bắt đầu. Chị Thảo không muốn nghe giải thích nội bộ quá dài.', 'Lần này bên em sẽ xử lý cụ thể thế nào? Chị cần câu trả lời nghe được ngay bây giờ.'),
  openScenario('business-stage-3', 3, 'biz-ops-vy', 'VẬN HÀNH QUÁ TẢI', 'Chọn ưu tiên vận hành, cắt việc ít tác động và nói rõ rủi ro nếu tăng trưởng quá nhanh.', 'Một chương trình bán hàng đang kéo đơn tăng mạnh, nhưng kho và chăm sóc khách hàng bắt đầu quá tải.', 'Bàn điều phối đầy ticket đỏ. Làm thêm cũng không đủ người, nên phải chọn phần cứu trước.', 'Nếu nguồn lực không đủ, em giữ phần nào, cắt phần nào và báo rủi ro ra sao?'),
  openScenario('business-stage-4', 4, 'mentor-nova', 'BẠN CÓ HỢP QUẢN TRỊ KHÔNG?', 'Nhìn lại cách bạn ra quyết định khi có số liệu, khách hàng và vận hành cùng tạo áp lực.', 'Sau ba tình huống kinh doanh, Mentor Nova muốn nghe bạn nói thật về cảm giác khi phải ra quyết định không đủ dữ liệu.', 'Phòng phỏng vấn cuối. Không còn khách hàng hay sếp dí, chỉ còn câu hỏi nghề nghiệp.', 'Trong ba tình huống vừa rồi, phần nào làm bạn thấy hứng thú nhất và phần nào làm bạn thấy ngợp?'),

  openScenario('architecture-stage-1', 1, 'arch-client-mai', 'NHÀ NHỎ NHƯNG YÊU CẦU RẤT NHIỀU', 'Khai thác nhu cầu thật của khách, ưu tiên công năng và không hứa thiết kế vượt giới hạn.', 'Khách muốn phòng khách rộng, bếp thoáng, góc làm việc và nhiều tủ, nhưng diện tích rất hạn chế.', 'Buổi gặp khách đầu tiên. Khách thích nhiều thứ, nhưng mặt bằng không nở ra được.', 'Nếu em là người thiết kế, em hỏi lại chị điều gì trước khi chốt phương án?'),
  openScenario('architecture-stage-2', 2, 'arch-senior-khoa', 'BẢN PHỐI CẢNH ĐẸP NHƯNG Ở KHÓ', 'Bảo vệ phương án thiết kế bằng công năng, luồng di chuyển và trải nghiệm sống thật.', 'Phối cảnh nhìn đẹp, nhưng senior architect phát hiện bố trí này có thể khiến sinh hoạt hằng ngày bất tiện.', 'Studio im lặng vài giây khi KTS Khoa zoom vào mặt bằng. Đẹp thì có đẹp, nhưng ở thật chưa chắc sướng.', 'Em giữ ý tưởng này thế nào, hay chỉnh phần nào để nó không chỉ đẹp trên ảnh?'),
  openScenario('architecture-stage-3', 3, 'arch-site-tuan', 'CÔNG TRƯỜNG BÁO KHÔNG THI CÔNG ĐƯỢC', 'Xử lý xung đột giữa bản vẽ, chi phí, an toàn và khả năng thi công.', 'Một chi tiết thiết kế nhìn rất đẹp nhưng đội công trường báo khó thi công và có rủi ro an toàn.', 'Điện thoại từ công trường gọi về. Nếu bạn cố giữ bản vẽ, chi phí và tiến độ có thể vỡ.', 'Em phản hồi công trường thế nào để vừa giữ tinh thần thiết kế vừa không liều?'),
  openScenario('architecture-stage-4', 4, 'mentor-nova', 'BẠN CÓ HỢP KIẾN TRÚC KHÔNG?', 'Nhìn lại xem bạn bị cuốn bởi thẩm mỹ, công năng hay áp lực thuyết phục khách.', 'Sau các tình huống thiết kế, Mentor Nova muốn biết phần nào khiến bạn có năng lượng thật.', 'Bản vẽ khép lại. Giờ đến phần khó hơn: nói thật mình thích nghề vì điều gì.', 'Bạn thấy mình thích phần sáng tạo ý tưởng, giải quyết công năng hay làm việc với khách hơn? Vì sao?'),

  openScenario('pharmacy-stage-1', 1, 'pharm-patient-long', 'KHÁCH ĐAU DẠ DÀY MUỐN MUA THUỐC NHANH', 'Hỏi đủ thông tin cơ bản trước khi tư vấn đau dạ dày, nhưng vẫn nói sao cho khách không khó chịu.', 'Anh Long nói đau vùng dạ dày sau khi ăn và muốn mua thuốc ngay. Nếu hỏi quá nhiều mà không giải thích, anh sẽ cáu.', 'Quầy thuốc đông khách. Anh Long đang ôm bụng, sốt ruột muốn mua thuốc đau dạ dày cho nhanh.', 'Em cần hỏi anh thêm gì trước khi tư vấn thuốc đau dạ dày? Nói sao để anh không thấy bị làm phiền?'),
  openScenario('pharmacy-stage-2', 2, 'pharm-senior-huong', 'TRIỆU CHỨNG CÓ DẤU HIỆU CẦN ĐI KHÁM', 'Nhận diện giới hạn tư vấn tại quầy và biết khi nào phải khuyên khách đi khám.', 'Một khách mô tả triệu chứng nghe có vẻ phổ biến, nhưng có vài dấu hiệu khiến dược sĩ phụ trách không yên tâm.', 'DS Hương đứng cạnh quan sát. Quầy đông, nhưng câu trả lời vội có thể gây rủi ro thật.', 'Với ca này, em tư vấn tại quầy hay khuyên đi khám? Em dựa vào dấu hiệu nào?'),
  openScenario('pharmacy-stage-3', 3, 'pharm-doctor-minh', 'ĐƠN THUỐC CÓ ĐIỂM CHƯA RÕ', 'Biết xác nhận lại khi đơn thuốc/tiền sử/tương tác chưa rõ thay vì tự suy đoán.', 'Một đơn thuốc có điểm khiến bạn băn khoăn: liều dùng hoặc thuốc dùng kèm chưa rõ.', 'Bạn đang gọi sang phòng khám. BS Minh không khó chịu, nhưng cần bạn nói rõ điểm cần xác nhận.', 'Em đang nghi ngờ điểm nào trong đơn này và cần bác sĩ xác nhận lại điều gì?'),
  openScenario('pharmacy-stage-4', 4, 'mentor-nova', 'BẠN CÓ HỢP NGÀNH DƯỢC KHÔNG?', 'Nhìn lại xem bạn có chịu được nhịp tư vấn nhanh nhưng phải cẩn trọng không.', 'Sau ba ca mô phỏng tại quầy, Mentor Nova muốn nghe bạn nói thật về cảm giác với trách nhiệm trong ngành Dược.', 'Không còn khách đang chờ. Chỉ còn câu hỏi: bạn có thấy mình phù hợp với kiểu cẩn thận này không?', 'Bạn thích phần tư vấn con người, phần kiểm tra an toàn, hay thấy áp lực vì sợ sai?'),

  openScenario('marketing-stage-1', 1, 'mkt-lead-khanh', 'CAMPAIGN TỤT ENGAGEMENT', 'Tìm insight và giả thuyết trước khi sửa content.', 'Campaign mới chạy nhưng engagement tụt. Cả team đang muốn đổi nội dung ngay.', 'Phòng campaign sáng đèn. Anh Khánh hỏi trước khi ai đó đốt thêm ngân sách.', 'Em kiểm tra insight nào trước khi đề xuất sửa campaign?'),
  openScenario('marketing-stage-2', 2, 'mkt-client-yen', 'KHÁCH KHÔNG DUYỆT THÔNG ĐIỆP', 'Thuyết phục khách bằng lý do người dùng hiểu được, không chỉ bằng câu chữ đẹp.', 'Khách thấy thông điệp chưa đủ rõ và sợ người xem không hiểu sản phẩm.', 'Cuộc gọi duyệt bài căng hơn dự kiến. Chị Yến không muốn nghe slogan bay bổng nữa.', 'Em sửa thông điệp thế nào để khách thấy rõ hơn mà vẫn giữ cá tính brand?'),
  openScenario('marketing-stage-3', 3, 'mkt-data-an', 'SỐ LIỆU NÓI NGƯỢC CẢM GIÁC', 'Biết dùng dữ liệu để kiểm tra giả thuyết marketing.', 'Team nghĩ content hay, nhưng data cho thấy người dùng không bấm.', 'An Data mở bảng chỉ số. Không khí bớt thơ mộng hẳn.', 'Nếu cảm giác của team khác với số liệu, em xử lý thế nào?'),

  openScenario('accounting-stage-1', 1, 'fin-chief-lam', 'BÁO CÁO LỆCH SỐ', 'Đối chiếu số liệu và xác định nguồn lệch trước khi chốt báo cáo.', 'File báo cáo gần xong nhưng tổng số đang lệch với chứng từ.', 'Kế toán trưởng nhìn đồng hồ. Không ai được chốt số bằng cầu nguyện.', 'Em kiểm tra nguồn lệch theo thứ tự nào?'),
  openScenario('accounting-stage-2', 2, 'fin-auditor-ngan', 'CHỨNG TỪ THIẾU', 'Biết xử lý khoản thiếu chứng từ đúng quy trình.', 'Một khoản chi có số tiền rõ nhưng chứng từ chưa đủ.', 'Chị Ngân đặt hồ sơ xuống bàn. Câu “em nghĩ là đúng” không có giá trị ở đây.', 'Em ghi nhận hoặc xử lý khoản này thế nào khi chứng từ chưa đủ?'),
  openScenario('accounting-stage-3', 3, 'fin-manager-trang', 'HẠN NỘP SÁT GIỜ', 'Ưu tiên phần rủi ro cao trước khi nộp báo cáo.', 'Không đủ thời gian kiểm hết mọi dòng. Finance Manager cần bạn chọn phần phải kiểm trước.', 'Deadline đang dí. Làm hết thì không kịp, làm ẩu thì nguy hiểm.', 'Nếu chỉ còn 30 phút, em kiểm phần nào trước và vì sao?'),

  openScenario('ecommerce-stage-1', 1, 'legal-senior-phuc', 'GIAN HÀNG CÓ TRAFFIC NHƯNG ÍT ĐƠN', 'Tìm điểm nghẽn conversion trước khi đốt thêm quảng cáo.', 'Sản phẩm có người xem nhưng ít người mua. Anh Huy cần bạn chỉ ra phần cần sửa trước.', 'Anh Huy mở dashboard sàn. Traffic không tệ, nhưng đơn hàng thì im lặng đáng sợ.', 'Em nhìn điểm nghẽn nào trước để tăng tỷ lệ mua?'),
  openScenario('ecommerce-stage-2', 2, 'legal-client-linh', 'KHÁCH BÁO GIAO SAI HÀNG', 'Xử lý khách bực, giữ đánh giá shop và sửa lỗi vận hành.', 'Một khách nhận sai mẫu và đang chuẩn bị đánh giá 1 sao.', 'Khung chat chăm sóc khách nhảy liên tục. Chị Mai không muốn nghe lý do nội bộ.', 'Shop xử lý cho chị thế nào, và bao giờ xong?'),
  openScenario('ecommerce-stage-3', 3, 'legal-compliance-an', 'FLASH SALE SẮP VỠ ĐƠN', 'Cân bằng tăng đơn, tồn kho, chat khách và vận chuyển.', 'Deal đang chạy tốt nhưng kho và chat bắt đầu nghẽn. Đẩy thêm đơn lúc này có thể phản tác dụng.', 'An Ops nhìn bảng tồn kho rồi thở dài. Bán thêm không khó, giao nổi mới khó.', 'Em chia nguồn lực thế nào để vừa giữ doanh thu vừa không vỡ trải nghiệm khách?'),

  openScenario('uiux-stage-1', 1, 'ux-lead-minh', 'FLOW ĐẸP NHƯNG USER BỊ KẸT', 'Quan sát hành vi người dùng và sửa flow dựa trên điểm kẹt thật.', 'Prototype nhìn đẹp, nhưng user test bỏ giữa chừng.', 'UX Lead Minh mở video test. Người dùng đã dừng đúng chỗ mà team tưởng là “dễ hiểu”.', 'Em xem hành vi nào trước và sửa flow theo hướng nào?'),
  openScenario('uiux-stage-2', 2, 'ux-user-mai', 'USER KHÔNG TÌM THẤY NÚT', 'Nói chuyện với user để hiểu vấn đề thay vì đổ lỗi người dùng.', 'Người dùng thử không tìm thấy nút chính dù team nghĩ nó rất nổi bật.', 'Chị Mai hơi bối rối, còn team đứng sau kính quan sát đang im lặng.', 'Em hỏi chị điều gì để hiểu vì sao chị không thấy nút đó?'),
  openScenario('uiux-stage-3', 3, 'ux-pm-trang', 'CHỈ ĐƯỢC SỬA MỘT FLOW', 'Chọn flow có tác động cao nhất và bảo vệ quyết định thiết kế.', 'Dev chỉ còn thời gian sửa một flow trước demo.', 'PM Trang muốn bạn chọn, không muốn nghe danh sách 10 thứ đều quan trọng.', 'Em chọn sửa flow nào trước và lấy bằng chứng gì để bảo vệ lựa chọn đó?'),
];

export function getRoleplayScenario(stageId: RoleplayStageId) {
  return roleplayScenarios.find((scenario) => scenario.id === stageId);
}

export function getRoleplayActor(actorId: RoleplayActorId) {
  return roleplayActors[actorId];
}
